app/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user

from sqlalchemy.exc import IntegrityError

import base64

from app.model import db, USER, SUBMISSION, COMMENT, TAGS, FOLLOWER
from app.forms import CreateContentForm, EditProfileForm, CommentForm
from app.utilities import UsernameValidation, PasswordValidation, organiseColumnImages, is_following

picTalk_bp = Blueprint('picTalk', __name__)


@picTalk_bp.route('/')
def home():
    return render_template('home.html', current_user=current_user)


@picTalk_bp.route('/search', methods=['GET', 'POST'])
def search():
    if request.method == "POST":
        query = request.form['search'].lower()

        if current_user.is_authenticated:  # Makes sure that current user is not included in the results
            users = USER.query.filter(
                USER.username.like(
                    f"%{query}%"),
                USER.username != current_user.username).all()
        else:
            users = USER.query.filter(USER.username.like(f"%{query}%")).all()

        tags = TAGS.query.filter(TAGS.tag.like(f"%{query}%")).all()
        return render_template(
            'search.html', users=users, tags=tags, query=query)

    return render_template('search.html')


@picTalk_bp.route('/gallery')
def gallery():
    images = SUBMISSION.query.order_by(SUBMISSION.created_at).all()

    base64_images_firstColumn = base64_images_secondColumn = base64_images_thirdColumn = []
    if images:
        base64_images = [
            {"id": image.submission_id,
             "data": base64.b64encode(image.image).decode("utf-8")}
            for image in images
        ]
        base64_images.reverse()

        base64_images_firstColumn = organiseColumnImages(base64_images)[0]
        base64_images_secondColumn = organiseColumnImages(base64_images)[1]
        base64_images_thirdColumn = organiseColumnImages(base64_images)[2]
    followed_count = 0
    base64_images_firstColumn_following = base64_images_secondColumn_following = base64_images_thirdColumn_following = []
    if current_user.is_authenticated:
        images_following = (
            SUBMISSION.query .join(
                FOLLOWER, FOLLOWER.followed_id == SUBMISSION.username_id) .filter(
                FOLLOWER.follower_id == current_user.username_id) .order_by(
                SUBMISSION.created_at) .all())
        base64_images_following = [
            {"id": image.submission_id,
             "data": base64.b64encode(image.image).decode("utf-8")}
            for image in images_following
        ]
        base64_images_following.reverse()

        base64_images_firstColumn_following = organiseColumnImages(
            base64_images_following)[0]
        base64_images_secondColumn_following = organiseColumnImages(
            base64_images_following)[1]
        base64_images_thirdColumn_following = organiseColumnImages(
            base64_images_following)[2]

        followed_count = FOLLOWER.query.filter_by(
            follower_id=current_user.username_id).count()
    return render_template(
        'gallery.html',
        user=current_user,
        followed_count=followed_count,

        images_firstColumn=base64_images_firstColumn,
        images_secondColumn=base64_images_secondColumn,
        images_thirdColumn=base64_images_thirdColumn,

        images_firstColumn_following=base64_images_firstColumn_following,
        images_secondColumn_following=base64_images_secondColumn_following,
        images_thirdColumn_following=base64_images_thirdColumn_following)


@picTalk_bp.route('/gallery/<string:tag>')
def gallery_tags(tag):
    tags = TAGS.query.filter_by(tag=tag).all()
    submission_ids = [tag.submission_id for tag in tags]

    base64_images_firstColumn_tag = base64_images_secondColumn_tag = base64_images_thirdColumn_tag = []
    if submission_ids:
        images_tag = SUBMISSION.query.filter(SUBMISSION.submission_id.in_(submission_ids)).all()

        base64_images_tag = [
            {"id": image.submission_id,
             "data": base64.b64encode(image.image).decode("utf-8")}
            for image in images_tag
        ]
        base64_images_tag.reverse()

        base64_images_firstColumn_tag = organiseColumnImages(
            base64_images_tag)[0]
        base64_images_secondColumn_tag = organiseColumnImages(
            base64_images_tag)[1]
        base64_images_thirdColumn_tag = organiseColumnImages(
            base64_images_tag)[2]

    return render_template(
        'gallery_tags.html',
        tag=tag,
        images_firstColumn_tag=base64_images_firstColumn_tag,
        images_secondColumn_tag=base64_images_secondColumn_tag,
        images_thirdColumn_tag=base64_images_thirdColumn_tag)


@picTalk_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == "POST":
        signup_username = request.form['signup-username'].lower()
        signup_psw = request.form['signup-psw']
        signup_pswConfirm = request.form['signup-pswConfirm']

        if signup_psw != signup_pswConfirm:
            flash('Passwords do not match.', 'warning')
            return render_template('signup.html')

        if UsernameValidation.validate(signup_username):
            flash('Username does not meet criteria.', 'warning')
            return render_template('signup.html')

        if PasswordValidation.validate(signup_psw):
            flash('Password does not meet criteria.', 'warning')
            return render_template('signup.html')

        existing_user = USER.query.filter_by(username=signup_username).first()
        if existing_user:
            flash('Username is already in use.', 'danger')
            return render_template('signup.html')

        # Only pass the username and unhashed password
        new_user = USER(username=signup_username, password=signup_psw, about_me="")
        db.session.add(new_user)
        db.session.commit()
        flash('Account created successfully! Please log in.', 'success')
        return redirect(url_for('picTalk.login'))

    return render_template("signup.html")


@picTalk_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        login_username = request.form['login-username'].lower()
        login_password = request.form['login-password']

        user = USER.query.filter_by(username=login_username).first()
        if user and user.check_password(login_password):
            login_user(user)
            flash('Logged in successfully.', 'success')
            return redirect(url_for('picTalk.home'))
        else:
            flash('Invalid username or password.', 'warning')

    return render_template('login.html')


@picTalk_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'info')
    return redirect(url_for('picTalk.home'))


@picTalk_bp.route('/profile/<string:username>')
def profile(username):
    user = USER.query.filter_by(username=username).first_or_404()
    submission_count = SUBMISSION.query.filter_by(
        username_id=user.username_id).count()

    images = SUBMISSION.query.filter_by(
        username_id=user.username_id).order_by(
        SUBMISSION.created_at).all()
    base64_images = [
        {"id": image.submission_id, "data": base64.b64encode(
            image.image).decode("utf-8")}
        for image in images
    ]
    base64_images.reverse()

    base64_images_firstColumn = organiseColumnImages(base64_images)[0]
    base64_images_secondColumn = organiseColumnImages(base64_images)[1]
    base64_images_thirdColumn = organiseColumnImages(base64_images)[2]

    check_following = False
    if current_user.is_authenticated:
        check_following = is_following(
            current_user.username_id, user.username_id)

    follower_count = FOLLOWER.query.filter_by(
        followed_id=user.username_id).count()
    followed_count = FOLLOWER.query.filter_by(
        follower_id=user.username_id).count()

    return render_template('profile.html', user=user,
                           submission_count=submission_count,
                           check_following=check_following,
                           follower_count=follower_count,
                           followed_count=followed_count,
                           images_firstColumn=base64_images_firstColumn,
                           images_secondColumn=base64_images_secondColumn,
                           images_thirdColumn=base64_images_thirdColumn)


@picTalk_bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()
        flash('Your changes have been saved.', 'success')
        return redirect(url_for('picTalk.profile',
                        username=current_user.username))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.about_me.data = current_user.about_me
    else:
        flash('Username did not meet criteria', 'warning')

    return render_template('edit_profile.html',
                           title='Edit Profile', form=form)


@picTalk_bp.route('/image/<int:submission_id>', methods=['GET', 'POST'])
@login_required
def view_post(submission_id):
    form = CommentForm()
    image = SUBMISSION.query.get(submission_id)
    base64_image = base64.b64encode(image.image).decode("utf-8")
    comments = COMMENT.query.filter_by(submission_id=submission_id).all()
    creator = USER.query.get(image.username_id)
    tags = TAGS.query.filter_by(submission_id=submission_id).all()

    if form.validate_on_submit():
        new_comment = COMMENT(comment=form.comment.data,
                              username_id=current_user.username_id,
                              submission_id=submission_id)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/bootstrap.min.css') }}">
    <!-- Base CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/base.css') }}">
    <!-- Variable CSS -->
    <!-- This is CSS for the specific file loaded into the template inheritance -->
    {% block variable_css %}{% endblock %}

    <link rel="icon" type="image/svg+xml" href="{{ url_for('static', filename = 'icons/favicon.svg') }}">

    <title>{% block title %}PicTalk{% endblock %}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg justify-content-center">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url_for('picTalk.home') }}">PicTalk</a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-between container-fluid" id="navbarSupportedContent">
                    <div class="container-fluid">
                        <form action="{{ url_for('picTalk.search') }}" method="POST" class="form-inline">
                            <div class="input-group">
                                <input class="form-control nav-form-searchBar" type="search" id="search" name="search"
                                    placeholder="Search tags or users" aria-label="Search">
    
                                <div class="input-group-append">
                                    <button class="btn nav-form-searchBtn" type="submit"><img
                                            src="{{ url_for('static', filename = 'icons/searchIcon.svg') }}"
                                            alt="Search Icon"></button>
                                </div>
                            </div>
                        </form>
                    </div>

                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('picTalk.gallery') }}">Gallery</a>
                        </li>

                        {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('picTalk.create') }}">Submit</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link"
                                    href="{{ url_for('picTalk.profile', username=current_user.username) }}">
                                    {{ current_user.username | truncate_username}}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('picTalk.logout') }}">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('picTalk.login') }}">Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}" id="flash-message">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}

        {% block main %}{% endblock %}
    </main>

    <footer>

    </footer>

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

    <script src="{{ url_for('static', filename = 'javascript/flashMessages.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

    {% block variable_js %}{% endblock %}
</body>

</html>

app/templates/edit_profile.html
{% extends "base.html" %}

<!-- Imports edit_profile.css -->
{% block variable_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/edit_profile.css') }}">
{% endblock %}

<!-- Sets title for edit_profile page -->
{% block title %}
Edit Profile
{% endblock %}

{% block main %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1>Edit Profile</h1>
            <form method="post">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}<br>
                    {{ form.username(class="form-control") }}<br>
                </div>
                <div class="form-group">
                    {{ form.about_me.label(class="form-control-label") }}<br>
                    {{ form.about_me(class="form-control", cols=50, rows=4) }}<br>
                </div>
                <div class="form-group">
                    {{ form.submit(class="btn btn-primary") }}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/gallery.html
{% extends 'base.html' %}

<!-- Imports gallery.css -->
{% block variable_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/gallery.css') }}">
{% endblock %}

<!-- Sets title for gallery page -->
{% block title %}
Gallery
{% endblock %}

<!-- Content for gallery page -->
{% block main %}

{% if current_user.is_authenticated %}
<div class="container container-tabs">
  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="pills-gallery-tab" data-bs-toggle="pill" data-bs-target="#pills-gallery"
        type="button" role="tab" aria-controls="pills-gallery" aria-selected="true">Gallery</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="pills-following-tab" data-bs-toggle="pill" data-bs-target="#pills-following"
        type="button" role="tab" aria-controls="pills-following" aria-selected="false">Following</button>
    </li>
  </ul>
</div>
{% endif %}

<div class="tab-content" id="pills-tabContent">
  <div class="tab-pane fade show active" id="pills-gallery" role="tabpanel" aria-labelledby="pills-gallery-tab">

    <div class="container container-title-gallery mb-3">
      <p class="display-6 fw-bold"> Gallery </p>
      <p>
        Welcome to PicTalk's vibrant Gallery page, where every image tells a story and every critique sparks creativity. From stunning
        landscapes to captivating portraits, our gallery is a dynamic showcase of artistic expression. Engage with
        fellow enthusiasts, share your thoughts, and unleash the power of constructive feedback.
      </p>
    </div>

    <div class="container container-gallery mb-3">
      <div class="row gx-3 mb-4">

        <div class="col column">
          {% for image in images_firstColumn %}
          <a href="{{ url_for('picTalk.view_post', submission_id=image.id) }}">
            <img src="data:image/png;base64, {{image.data}}" class="image" style="width:100%">
          </a>
          {% endfor %}
        </div>

        <div class="col column">
          {% for image in images_secondColumn %}
          <a href="{{ url_for('picTalk.view_post', submission_id=image.id) }}">
            <img src="data:image/png;base64, {{image.data}}" class="image" style="width:100%">
          </a>
          {% endfor %}
        </div>

        <div class="col column">
          {% for image in images_thirdColumn %}
          <a href="{{ url_for('picTalk.view_post', submission_id=image.id) }}">
            <img src="data:image/png;base64, {{image.data}}" class="image" style="width:100%">
          </a>
          {% endfor %}
        </div>

      </div>
    </div>

  </div>

  <div class="tab-pane fade" id="pills-following" role="tabpanel" aria-labelledby="pills-following-tab">
    {% if followed_count != 0 %}
    <div class="container container-title-gallery mb-3">
      <p class="display-6 fw-bold"> Following </p>
      <p>
        Discover a selection of images from the creators you follow.
      </p>
    </div>

    <div class="container container-gallery mb-3">
      <div class="row gx-3 mb-4">

        <div class="col column">
          {% for image in images_firstColumn_following %}
          <a href="{{ url_for('picTalk.view_post', submission_id=image.id) }}">
            <img src="data:image/png;base64, {{image.data}}" class="image" style="width:100%">
          </a>
          {% endfor %}
        </div>

        <div class="col column">
          {% for image in images_secondColumn_following %}
          <a href="{{ url_for('picTalk.view_post', submission_id=image.id) }}">
            <img src="data:image/png;base64, {{image.data}}" class="image" style="width:100%">
          </a>
          {% endfor %}
        </div>

        <div class="col column">
          {% for image in images_thirdColumn_following %}
          <a href="{{ url_for('picTalk.view_post', submission_id=image.id) }}">
            <img src="data:image/png;base64, {{image.data}}" class="image" style="width:100%">
          </a>
          {% endfor %}
        </div>

      </div>
    </div>
    {% else %}
    <div class="container container-title-gallery mb-3">
      <p class="display-6 fw-bold"> Following </p>
      <p>
        You currently do not follow anyone.
      </p>
    </div>
    {% endif %}
  </div>

</div>

{% endblock %}

{% block variable_js %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock %}

app/templates/gallery_tags.html
{% extends 'base.html' %}

<!-- Imports gallery.css -->
{% block variable_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/gallery.css') }}">
{% endblock %}

<!-- Sets title for gallery page -->
{% block title %}
Tag: {{ tag }}
{% endblock %}

<!-- Content for gallery page -->
{% block main %}
<div class="container container-title-gallery mb-3">
    <p class="display-6 fw-bold"> Images tagged with '{{ tag }}' </p>
</div>

<div class="container container-gallery mb-3">
    <div class="row gx-3 mb-4">

        <div class="col column">
            {% for image in images_firstColumn_tag %}
            <a href="{{ url_for('picTalk.view_post', submission_id=image.id) }}">
                <img src="data:image/png;base64,{{image.data}}" class="image" style="width:100%" alt="first column image">
            </a>
            {% endfor %}
        </div>

        <div class="col column">
            {% for image in images_secondColumn_tag %}
            <a href="{{ url_for('picTalk.view_post', submission_id=image.id) }}">
                <img src="data:image/png;base64,{{image.data}}" class="image" style="width:100%" alt="second column image">
            </a>
            {% endfor %}
        </div>

        <div class="col column">
            {% for image in images_thirdColumn_tag %}
            <a href="{{ url_for('picTalk.view_post', submission_id=image.id) }}">
                <img src="data:image/png;base64,{{image.data}}" class="image" style="width:100%" alt="third column image">
            </a>
            {% endfor %}
        </div>

    </div>
</div>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}

<!-- Imports home.css -->
{% block variable_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/home.css') }}">
{% endblock %}

<!-- Sets title for home page -->
{% block title %}
PicTalk
{% endblock %}

<!-- Main content for login page -->
{% block main %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="first-slide" src="../static/images/Uluru.jpg" alt="First slide - Uluru"> 
      <div class="container">
        <div class="carousel-caption">
          <h1 class="title-slide-1 display-3 rotate-text">PicTalk</h1>
          <p id="slogan">Exchange, Engage, Elevate</p>
          <p id="caption1">Your go-to place for all things related to photography and visual storytelling.</p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="second-slide" src="../static/images/2ndSlide.jpg" alt="Second slide - Mountain"> 
      <div class="container">
        <div class="carousel-caption">
          <h1>Create An Account Now!</h1>
          <p><a class="btn btn-lg btn-professional" href="{{ url_for('picTalk.signup') }}" role="button">Sign up today</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="third-slide" src="../static/images/3rdSlide.jpg" alt="Third slide - Coast"> 
      <div class="container">
        <div class="carousel-caption text-right">
          <h1>Browse Our Gallery</h1>
          <h4>Looking for inspiration?</h4>
          <p><a class="btn btn-lg btn-professional" href="{{ url_for('picTalk.gallery') }}" role="button">Click Here!</a></p>
        </div>
      </div>
    </div>
  </div>

  <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container-fluid">
  <div class="row">

    <div class="col-1 outerSection"></div>
    <div class="col-10 middleSection"></div>
    <div class="col-1 outerSection"></div>

  </div>
</div>

<div class="container">
  <div class="row">

    <div class="col-md-4">
      <img class="rounded-circle" src="../static/images/remote-team-collaberate.jpg" alt="People collaberating"
        width="140" height="140">
      <h2>Your Visuals for Feedback</h2>
      <p>Share your photographs or artistic creations with our community to receive thoughtful and detailed feedback,
        guidance, and inspiration for your work. </p>
    </div>

    <div class="col-md-4">
      <img class="rounded-circle" src="../static/images/artGallery.jpg" alt="Art gallery" width="140" height="140">
      <h2>Learn from Inspiring Examples</h2>
      <p>Receive constructive feedback on your visuals, highlighting both their strengths and areas for improvement. Our
        goal is to help you grow and refine your artistic vision. </p>
    </div>

    <div class="col-md-4">
      <img class="rounded-circle" src="../static/images/feedbackjpg.jpg" alt="Person connected to others with thoughts"
        width="140" height="140">
      <h2>Get Personalized Advice from Experts</h2>
      <p>Our community includes experienced artists who can provide you with tailored advice and suggestions to enhance
        your skills and creativity.</p>
    </div>

  </div>
</div>

<hr class="featurette-divider">
<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading"> Submit Your Art. <span class="text-muted"> Receive Feedback From Our Hearts. </span>
    </h2>
    <p class="bottom-text"> Join PicTalk today, a vibrant community where your creativity shines. Share your visual stories, whether they're stunning landscapes, captivating portraits, or unique perspectives. 
      Receive thoughtful feedback from fellow casual photographers and seasoned experts, helping you refine your craft. 
      Your art deserves to be seen and celebrated. Submit your photos get valuable advice, and connect with like-minded individuals who share your passion for visual storytelling. 
      Join PicTalk today and let your artistry unfold!</p>
  </div>
  <div class="col-md-5">
    <img class="featurette-image img-fluid mx-auto" src="../static/images/vertLandscape.jpg"
      alt="Vertical Landscape of Faroe Islands" style="height: 600px; padding-left: 1cm;">
  </div>
</div>

{% endblock %}

app/templates/profile.html
{% extends 'base.html' %}

<!-- Imports profile.css -->
{% block variable_css %}
<link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/profile.css') }}">
{% endblock %}

<!-- Sets title for profile page -->
{% block title %}
{{ user.username }}
{% endblock %}

<!-- Main content for profile page -->
{% block main %}
<div class="container container-profile">
    <div class="container container-profile-header">
        <div class="row">

            <div class="col">
                <p class="display-6 fw-bold USERNAME"> {{ user.username }} </p>
                {% if user == current_user %}
                <p class="editProfLink"><a href="{{ url_for('picTalk.edit_profile') }}">Edit your profile</a></p>
                {% endif %}
            </div>

            <div class="col">
                <div class="row">
                    <div class="col profile-details">
                        {{ submission_count }}
                        <br>
                        Submissions
                    </div>
                    <div class="col profile-details">
                        {{ follower_count | format_profileNumbers }}
                        <br>
                        Followers
                    </div>
                    <div class="col profile-details">
                        {{ followed_count | format_profileNumbers }}
                        <br>
                        Following
                    </div>
                </div>
            </div>

        </div>
        {% if (current_user.is_authenticated) and (current_user != user) %}
            <div class="container container-profile-follower-button">
                {% if check_following %}
                    <form action="{{ url_for('picTalk.unfollow', username_id = user.username_id) }}" method="POST">
                        <input type="hidden" name="follower_id" value="{{ current_user.username_id }}">
                        <button type="submit" class="btn btn-lg btn-block">Unfollow</button>
                    </form>
                {% else %}
                    <form action="{{ url_for('picTalk.follow', username_id = user.username_id) }}" method="POST">
                        <input type="hidden" name="followed_id" value="{{ current_user.username_id }}">
                        <button type="submit" class="btn btn-lg btn-block">Follow</button>
                    </form>
                {% endif %}
            </div>
        {% endif %}
        <div class="container container-about-me ">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">About Me</div>
                        <div class="card-body">
                            {% if user.about_me %}
                            <p>{{ user.about_me }}</p>
                            {% else %}
                            <p>I love PicTalk!</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
    <div class="container container-profile-body">
        <div class="row gx-3 mb-4">

            <div class="col column">
                {% for image in images_firstColumn %}
                    <a href="{{ url_for('picTalk.view_post', submission_id=image.id) }}">
                        <img src="data:image/png;base64,{{image.data}}" class="image" style="width:100%" alt="first column image">
                    </a>
                {% endfor %}
            </div>

            <div class="col column">
                {% for image in images_secondColumn %}
                    <a href="{{ url_for('picTalk.view_post', submission_id=image.id) }}">
                        <img src="data:image/png;base64,{{image.data}}" class="image" style="width:100%" alt="second column image">
                    </a>
                {% endfor %}
            </div>

            <div class="col column">
                {% for image in images_thirdColumn %}
                    <a href="{{ url_for('picTalk.view_post', submission_id=image.id) }}">
                        <img src="data:image/png;base64,{{image.data}}" class="image" style="width:100%" alt="third column image">
                    </a>
                {% endfor %}
            </div>

        </div>
    </div>
</div>
{% endblock %}